version: '3'

services:
  db:
    image: mysql:8.0.0
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_TCP_PORT=3306


  mvc:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "8888:80"
    restart: always
    environment:
      - DBHOST=db
      - DBPORT=3306
      - DBPASSWORD=secret
      - ASPNETCORE_ENVIRONMENT=Production
      - APPSETTING_DB_TYPE=mysql
