version: '3'

services:
  db:
    image: microsoft/mssql-server-linux
    restart: always
    ports: 
      - "1433:1433"
    environment:
      - SA_PASSWORD=Sql!Expre55
      - ACCEPT_EULA=Y
      


  mvc:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "8888:80"
    restart: always
    environment:
      - DBHOST=db
      - DBNAME=openvoting
      - DBPORT=1433
      - DBUSERNAME=sa
      - DBPASSWORD=Sql!Expre55
      - ASPNETCORE_ENVIRONMENT=Production
      - APPSETTING_DB_TYPE=mssql
